import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen `}>

        <div>
          <img src="/background.png" className=" h-screen w-full fixed top-0 left-0 -z-50" />
        </div>
        <Navbar />
        <div className=" min-h-screen">
          {children}
        </div>

        <Footer />


      </body>
    </html>
  );
}
